# Generated by Django 5.0.6 on 2026-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('calm', 'Calm'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry')], max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_mood_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
